### ISSUE TITLE
app crashing - stacktrace given

### ISSUE THREAD

**Issue by suresh-s** [UrbanChrisy/Exposure-Vidsta#5]
FATAL EXCEPTION: main
                                                                                          Process: nz.co.delacour.exposurevideoplayersample, PID: 17311
                                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{nz.co.delacour.exposurevideoplayersample/nz.co.delacour.exposurevideoplayer.ExposureStandalonePlayer}: java.lang.ClassCastException: nz.co.delacour.exposurevidsta.Vidsta cannot be cast to nz.co.delacour.exposurevideoplayer.ExposureVideoPlayer
                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                           Caused by: java.lang.ClassCastException: nz.co.delacour.exposurevidsta.Vidsta cannot be cast to nz.co.delacour.exposurevideoplayer.ExposureVideoPlayer
                                                                                              at nz.co.delacour.exposurevideoplayer.ExposureStandalonePlayer.onCreate(ExposureStandalonePlayer.java:20)
                                                                                              at android.app.Activity.performCreate(Activity.java:5990)
                                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by UrbanChrisy** [comment]
Ah fuck, give me a Mo I fucked up.

**Comment by UrbanChrisy** [comment]
Are you using a pull version of the code from github or the version on JCenter?

**Comment by UrbanChrisy** [comment]
Holla, can you post your implementation code please.

**Comment by suresh-s** [comment]
I have downloaded as zip file from Master branch

**Comment by suresh-s** [comment]
Thank you for quick reply

**Comment by UrbanChrisy** [comment]
So, I have update the docs, I have just recently changed the naming on the library. In doing so fucked up.
So have a look at the docs.

**Comment by UrbanChrisy** [comment]
Any Luck?

**Comment by UrbanChrisy** [comment]
If no response by tomorrow I will be closing this issue as solved.

**Comment by suresh-s** [comment]
Please don't close today.  I will check today evening and  let you know
